# Generated by Django 3.2 on 2022-08-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahpril', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
