# Generated by Django 3.2 on 2022-08-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahpril', '0002_auto_20220803_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
