# Generated by Django 3.2 on 2022-08-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_auto_20220801_0918'),
        ('kahpril', '0004_quiz_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
