# Generated by Django 3.2 on 2022-08-04 06:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('kahpril', '0006_auto_20220804_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tests',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
